server:
  port: 8761

eureka:
  instance:
    hostname: 
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  
      
      
spring:
  profiles:
    active: dev
        